// @system — product identity config (template defaults)
// DO NOT edit this file for product-specific values — use @custom/info.js instead.
// This file is overwritten during template sync.
export const info = {
  name: 'Informational Template',
  tagline: 'A complete website for your business',
  description: 'an informational website with contact form, team, services and map',
  companyAddress: '',
  legalEffectiveDate: 'April 19, 2026',
  url: import.meta.env.VITE_APP_URL ?? 'http://localhost:5173',
  supportEmail: 'hello@producttemplate.com',
  // Social links — set product URLs in @custom/info.js. Omit keys to hide icons.
  social: {},
  // Brand colors — must match primaryColor / accentColor from products table.
  // Products override in @custom/info.js. CSS vars are injected automatically (see main.jsx).
  brandColor: '#64748B',
  accentColor: '#94A3B8',
  // Default theme — must match default_theme from products table.
  // Products override in @custom/info.js. Drives ThemeProvider initial state.
  defaultTheme: 'light',
  // Logo paths — auto-asset pipeline reads from /assets/logos/ (source: assets/logos/).
  // Products drop logo files in assets/logos/ and the template serves them everywhere.
  // Products override in @custom/info.js to use their own logos.
  logo: '/assets/logos/logo-mark.svg',
  logoDark: '/assets/logos/logo-white.svg',
  logoWhite: '/assets/logos/logo-white.svg',
  // Auth page — left brand panel content. Products override in @custom/info.js.
  auth: {
    badge: 'Full-stack SaaS starter',
    description: 'Auth, billing, teams, and email already built and tested. You write the feature that makes your product unique.',
    features: [
      'Auth with OAuth, TOTP and sessions',
      'Stripe billing wired end-to-end',
      'Deploy anywhere in one command',
    ],
    testimonial: {
      quote: 'We had auth, billing, and teams running in one afternoon. Three months later we had paying customers.',
      name: 'James R.',
      role: 'Founder, Launchpad.io',
      initials: 'JR',
    },
    stats: [
      { val: 'Auth', sub: 'OAuth + TOTP' },
      { val: 'Billing', sub: 'Stripe ready' },
      { val: 'Deploy', sub: 'One command' },
    ],
  },
  // Subscription plans — used by isRouteLocked() for route-based feature gating.
  // Products define their plans in @custom/info.js.
  // Each plan: { name, priceId?, noAllowedRoutes: ['/app/route-to-lock', '/app/admin/*'] }
  // noAllowedRoutes = routes that this plan CANNOT access (locked behind higher plan).
  // Example: free plan locks /app/admin/*, /app/integrations, /app/api-keys
  plans: [],
}
