// @generated — informational site content from the repo-root brand.json `site` block.
// GENERATED by scripts/apply-brand.js — DO NOT EDIT BY HAND; edit brand.json and run `npm run apply-brand`.
//
// Layer 2 of 3 in client/src/config/index.js (lowest → highest precedence):
//   content/@system/site.js  →  THIS FILE  →  content/@custom/site.js
// Objects merge per key, arrays replace, unset keys fall through (scripts/lib/site-brand.cjs).
// Company: Informational Template

export default {
  "locale": "en",
  "nav": {
    "links": [
      {
        "label": "About",
        "href": "#about"
      },
      {
        "label": "Services",
        "href": "#services"
      },
      {
        "label": "Team",
        "href": "#team"
      },
      {
        "label": "Testimonials",
        "href": "#testimonials"
      },
      {
        "label": "Contact",
        "href": "#contact"
      }
    ]
  },
  "contact": {
    "phone": "+351 210 000 000",
    "address": {
      "lines": [
        "Rua do Norte 42, 3º",
        "1200-286 Lisboa",
        "Portugal"
      ],
      "street": "Rua do Norte 42, 3º",
      "postalCode": "1200-286",
      "city": "Lisboa",
      "country": "Portugal"
    },
    "hours": [
      "Monday – Friday, 09:00 – 18:00 WET",
      "Closed on public holidays"
    ],
    "openingHours": [
      "Mo-Fr 09:00-18:00"
    ]
  },
  "seo": {
    "titleTemplate": "{name} - {tagline}",
    "ogImage": "/assets/og/og-image.png",
    "businessType": "ProfessionalService"
  },
  "analytics": {
    "provider": "none"
  }
}
