// @generated — informational site content from the repo-root brand.json `site` block.
// GENERATED by scripts/apply-brand.js — DO NOT EDIT BY HAND; edit brand.json and run `npm run apply-brand`.
//
// Layer 2 of 3 in client/src/config/index.js (lowest → highest precedence):
//   content/@system/site.js  →  THIS FILE  →  content/@custom/site.js
// Objects merge per key, arrays replace, unset keys fall through (scripts/lib/site-brand.cjs).
// Company: Creative Portfolio

export default {
  "locale": "en",
  "nav": {
    "links": [
      {
        "label": "Work",
        "href": "#work"
      },
      {
        "label": "About",
        "href": "#about"
      },
      {
        "label": "Services",
        "href": "#services"
      },
      {
        "label": "Contact",
        "href": "#contact"
      }
    ]
  },
  "contact": {
    "phone": "+1 000 000 0000",
    "address": {
      "lines": [
        "123 Creative Ave",
        "10001 New York",
        "NY",
        "United States"
      ],
      "street": "123 Creative Ave",
      "postalCode": "10001",
      "city": "New York",
      "region": "NY",
      "country": "United States"
    },
    "hours": [
      "Monday – Friday, 09:00 – 18:00 EST",
      "Closed on public holidays"
    ],
    "openingHours": [
      "Mo-Fr 09:00-18:00"
    ]
  },
  "footer": {
    "tagline": "Let's create something amazing together"
  },
  "seo": {
    "titleTemplate": "{name} - {tagline}",
    "ogImage": "/assets/og/og-image.png",
    "businessType": "ProfessionalService"
  },
  "analytics": {
    "provider": "none"
  }
}
