#!/usr/bin/env node
/**
 * Auto-generate barrel files for @system components and routes
 * Usage: node generate-barrels.js [--components] [--routes] [--pages] [--server-routes]
 * If no flags given, generates all barrels
 */

const fs = require('fs')
const path = require('path')

const TEMPLATE_DIR = path.resolve(__dirname, '../..')
const COMPONENT_DIRS = [
  'client/src/app/components/@system',
  'client/src/app/hooks/@system',
  'client/src/app/store/@system',
  'client/src/app/lib/@system',
]

/**
 * List direct subdirectories of a directory
 * Each subdirectory is assumed to export via its index.jsx|js file
 */
function getExportables(dirPath) {
  const fullPath = path.join(TEMPLATE_DIR, dirPath)

  if (!fs.existsSync(fullPath)) {
    return []
  }

  try {
    return fs
      .readdirSync(fullPath, { withFileTypes: true })
      .filter(
        (d) =>
          d.isDirectory() &&
          !d.name.startsWith('.') &&
          !d.name.startsWith('@') &&
          (fs.existsSync(path.join(fullPath, d.name, 'index.jsx')) ||
            fs.existsSync(path.join(fullPath, d.name, 'index.js')) ||
            fs.existsSync(path.join(fullPath, d.name, 'index.ts')) ||
            fs.existsSync(path.join(fullPath, d.name, 'index.tsx')))
      )
      .map((d) => d.name)
  } catch (err) {
    console.error(`Error reading ${fullPath}:`, err.message)
    return []
  }
}

/**
 * Generate barrel for a single directory (e.g., components/@system)
 */
function generateBarrel(dirPath) {
  const exports = getExportables(dirPath)

  if (exports.length === 0) {
    console.log(`  [${dirPath}] No exportable subdirectories found`)
    return null
  }

  const lines = [
    '// @system — Auto-generated barrel (do not edit manually)',
    '// Generated by: scripts/@system/generate-barrels.js',
    '',
    ...exports.map((name) => `export * from './${name}'`),
    '',
  ]

  return lines.join('\n')
}

/**
 * Auto-discover pages from pages/@system and pages/@custom directories
 */
function discoverPages() {
  const pagesDir = path.join(TEMPLATE_DIR, 'client/src/app/pages')
  const pages = {}

  for (const pageType of ['app', 'static']) {
    const typePath = path.join(pagesDir, pageType)
    if (!fs.existsSync(typePath)) continue

    for (const variant of ['@system', '@custom']) {
      const variantPath = path.join(typePath, variant)
      if (!fs.existsSync(variantPath)) continue

      const pageNames = fs
        .readdirSync(variantPath, { withFileTypes: true })
        .filter(
          (d) =>
            d.isDirectory() &&
            !d.name.startsWith('.') &&
            !d.name.startsWith('@') &&
            (fs.existsSync(path.join(variantPath, d.name, 'index.jsx')) ||
              fs.existsSync(path.join(variantPath, d.name, 'index.js')))
        )
        .map((d) => d.name)

      if (!pages[pageType]) pages[pageType] = {}
      pages[pageType][variant] = pageNames
    }
  }

  return pages
}

/**
 * Auto-discover API modules in server/src/api/@system/
 * Detects directories with index.js or router.js, and standalone .js files
 */
function discoverServerRoutes() {
  const apiDir = path.join(TEMPLATE_DIR, 'server/src/api/@system')

  if (!fs.existsSync(apiDir)) {
    console.log('  [server routes] server/src/api/@system/ not found')
    return []
  }

  const entries = fs.readdirSync(apiDir, { withFileTypes: true })
  const routes = []

  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name.startsWith('@')) continue

    if (entry.isDirectory()) {
      const hasRouter = fs.existsSync(path.join(apiDir, entry.name, 'router.js'))
      const hasIndex = fs.existsSync(path.join(apiDir, entry.name, 'index.js'))

      if (hasRouter) {
        routes.push({ name: entry.name, requirePath: `../../api/@system/${entry.name}/router` })
      } else if (hasIndex) {
        routes.push({ name: entry.name, requirePath: `../../api/@system/${entry.name}` })
      }
    } else if (entry.isFile() && entry.name.endsWith('.js')) {
      const name = entry.name.replace(/\.js$/, '')
      routes.push({ name, requirePath: `../../api/@system/${name}` })
    }
  }

  routes.sort((a, b) => a.name.localeCompare(b.name))
  return routes
}

/**
 * Generate server/src/routes/@system/index.js from discovered API modules
 */
function generateServerRoutes() {
  const routes = discoverServerRoutes()

  if (routes.length === 0) {
    console.log('  [server routes] No API modules found')
    return null
  }

  // Each router is mounted through `mount(name, path)`, which consults the
  // brand.json feature-module map (lib/@system/Helpers/modules.js →
  // ROUTER_MODULES). Routers whose module is switched off are neither mounted
  // nor even require()d, so a brochure site never loads Stripe/Polar/etc. code.
  // Routers not present in ROUTER_MODULES are always mounted.
  const lines = [
    '// @system — Auto-generated barrel (do not edit manually)',
    '// Generated by: scripts/@system/generate-barrels.js',
    '//',
    '// Feature modules: routers are mounted only when their module is enabled in',
    '// brand.json `modules` (see lib/@system/Helpers/modules.js → ROUTER_MODULES).',
    '// Disabled routers are not require()d at all.',
    '',
    "const express = require('express')",
    "const { isRouterEnabled } = require('../../lib/@system/Helpers/modules')",
    'const router = express.Router()',
    '',
    'function mount(name, requirePath) {',
    '  if (isRouterEnabled(name)) router.use(require(requirePath))',
    '}',
    '',
    ...routes.map((r) => `mount('${r.name}', '${r.requirePath}')`),
    '',
    'module.exports = router',
    '',
  ]

  return lines.join('\n')
}

// Main execution
const args = process.argv.slice(2)
const shouldGenAll = args.length === 0
const shouldGenComponents = shouldGenAll || args.includes('--components')
const shouldGenRoutes = shouldGenAll || args.includes('--routes')
const shouldGenPages = shouldGenAll || args.includes('--pages')
const shouldGenServerRoutes = shouldGenAll || args.includes('--server-routes')

let count = 0

if (shouldGenComponents) {
  COMPONENT_DIRS.forEach((dir) => {
    const barrel = generateBarrel(dir)
    if (barrel) {
      const barrelPath = path.join(TEMPLATE_DIR, dir, 'index.js')
      fs.writeFileSync(barrelPath, barrel)
      console.log(`✓ Generated ${dir}/index.js`)
      count++
    }
  })
}

if (shouldGenPages) {
  // NOTE: client/src/app/routes/@system/AppRoutes.jsx is intentionally NOT
  // regenerated here. It is a hand-authored, runtime-authoritative route table
  // that carries bespoke layout chrome (PageLayout S/A/P wrappers), GuestRoute
  // auth gating, per-route ordering and routes that a page-directory discovery
  // pass cannot reproduce (e.g. /dpa, /2fa/verify, /help/:slug). Overwriting it
  // here used to strip those wrappers and drop routes, so page auto-discovery
  // is now left to the committed manifest.json / discovery.js instead.
  const discovered = discoverPages()
  const staticCount = discovered.static?.['@system']?.length || 0
  console.log(
    `[pages] AppRoutes.jsx is hand-authored and left untouched (${staticCount} static page dirs ignored)`
  )
}

if (shouldGenServerRoutes) {
  const serverRoutes = generateServerRoutes()
  if (serverRoutes) {
    const serverRoutesPath = path.join(TEMPLATE_DIR, 'server/src/routes/@system/index.js')
    fs.writeFileSync(serverRoutesPath, serverRoutes)
    console.log(`✓ Generated server/src/routes/@system/index.js`)
    count++
  }
}

console.log(`Generated ${count} barrel file(s).`)
