// @custom — product identity for Informational Template
// GENERATED by scripts/apply-brand.js from the repo-root brand.json — DO NOT EDIT BY HAND.
//
// Regenerated on every prebuild (scripts/prebuild.js → apply-brand.js). Change
// identity, colours, fonts and theme in brand.json; put copy in
// config/@custom/text and content/@custom; put styles in styles/@custom/general.css.
// To stop regeneration for a bespoke file put a comment line reading
//   // apply-brand: keep
// within the first 10 lines.
//
// Consumed by client/src/config/index.js as { ...systemInfo, ...customInfo }.
// The legacy `info` export is kept for older importers.

import { info as baseInfo } from "../@system/info";

export const customInfo = {
  name: "Informational Template",
  tagline: "A complete website for businesses that need to be found, trusted and contacted",
  description: "Informational website template for VC firms, professional services, restaurants, trades and portfolios: hero, about, services, team, testimonials, contact form with admin inbox, and an API-key-free map embed. Built on the same authenticated Express + React foundation as the SaaS template, so auth, admin and legal pages are already there.",
  // Logo paths are served from /assets/logos (webpack copies assets/logos there).
  logo: "/assets/logos/logo-mark.svg",
  logoUrl: "/assets/logos/logo.svg",
  logoDark: "/assets/logos/logo-on-dark.svg",
  logoWhite: "/assets/logos/logo-on-dark.svg",
  favicon: "/assets/favicons/favicon.svg",
  defaultTheme: "light",
  brandColor: "#64748B",
  accentColor: "#94A3B8",
  brandFonts: {
    heading: "Inter",
    body: "Inter",
    mono: "JetBrains Mono",
  },
  auth: {
    ...baseInfo.auth,
    // Never ship fabricated social proof — products add real quotes in @custom/text.
    testimonial: null,
  },
};

export const info = { ...baseInfo, ...customInfo };
