/**
 * site-brand.cjs — brand.json `site` block → informational content layer.
 *
 * Pure functions only (no fs, no Node built-ins) so this module is safe to import
 * from the browser bundle (client/src/config/index.js), from scripts/apply-brand.js
 * and from client/webpack.config.mjs alike. The three consumers must agree on two
 * things, and this file is where they agree:
 *
 *   1. deepMerge — the layering rule for site content. Objects merge key by key,
 *      arrays are replaced wholesale, `undefined`/missing keys never clobber.
 *      Layers, lowest to highest:
 *        content/@system/site.js      template defaults ("Northwind Advisory")
 *        content/@generated/site.brand.js   emitted from brand.json `site` (apply-brand.js)
 *        content/@custom/site.js      hand-written product overrides
 *
 *   2. brandSiteToContent — the mapping from the provisioning-friendly shape Orkosi
 *      writes into brand.json (`site: { locale, nav, contact, social, footer, seo,
 *      analytics }`) to the content model SitePage renders. Empty strings, empty
 *      arrays and empty objects are pruned so an unset brand.json field falls
 *      through to the layer below instead of blanking it.
 *
 * brand.json `site` schema (all keys optional):
 *   locale     BCP-47 tag ("en", "pt-PT") → <html lang>, og:locale, JSON-LD inLanguage
 *   nav        [{ label, href }]           → nav.links (replaces the default list)
 *   navCta     { label, href }             → nav.ctaLabel / nav.ctaHref
 *   contact    { email, phone, address, hours[], openingHours[] }
 *              address: string | string[] | { lines[], street, postalCode, city, region, country }
 *              hours: display strings; openingHours: schema.org format ("Mo-Fr 09:00-18:00")
 *   social     { linkedin, twitter, github, youtube, instagram, facebook, email } → footer.social
 *   footer     { tagline, copyright, columns[], legalLinks[] }
 *   seo        { titleTemplate, description, ogImage, businessType }
 *              titleTemplate placeholders: {name} {tagline}; businessType is a schema.org
 *              type (ProfessionalService, LocalBusiness, Restaurant, LegalService, …)
 *   analytics  { provider: "none" | "plausible" | "umami", id }
 */

'use strict'

const SITE_GENERATED_MARKER = 'GENERATED by scripts/apply-brand.js'

const SOCIAL_KEYS = ['linkedin', 'twitter', 'github', 'youtube', 'instagram', 'facebook', 'email']
const ANALYTICS_PROVIDERS = ['none', 'plausible', 'umami']
const DEFAULT_BUSINESS_TYPE = 'ProfessionalService'
const SCHEMA_TYPE_RE = /^[A-Z][A-Za-z0-9]{2,60}$/

function isPlainObject(v) {
  return v !== null && typeof v === 'object' && !Array.isArray(v)
}

/** Deep merge: objects merge per key, arrays replace, undefined never overwrites. */
function deepMerge(target, source) {
  if (!isPlainObject(source)) return target
  const result = isPlainObject(target) ? { ...target } : {}
  for (const key of Object.keys(source)) {
    const value = source[key]
    if (value === undefined) continue
    if (isPlainObject(value) && isPlainObject(result[key])) {
      result[key] = deepMerge(result[key], value)
    } else {
      result[key] = value
    }
  }
  return result
}

/** Merge the three site content layers (lowest precedence first). */
function mergeSiteLayers(system, generated, custom) {
  return deepMerge(deepMerge(system || {}, generated || {}), custom || {})
}

const str = (v) => (typeof v === 'string' ? v.trim() : '')
const strList = (v) => {
  if (typeof v === 'string') return v.trim() ? [v.trim()] : []
  return Array.isArray(v) ? v.map(str).filter(Boolean) : []
}

/** Remove '', [], {}, null and undefined recursively so unset keys do not clobber lower layers. */
function prune(value) {
  if (Array.isArray(value)) {
    const arr = value.map(prune).filter((v) => v !== undefined)
    return arr.length ? arr : undefined
  }
  if (isPlainObject(value)) {
    const out = {}
    for (const key of Object.keys(value)) {
      const v = prune(value[key])
      if (v !== undefined) out[key] = v
    }
    return Object.keys(out).length ? out : undefined
  }
  if (value === null || value === undefined) return undefined
  if (typeof value === 'string') return value.trim() ? value.trim() : undefined
  return value
}

function linkList(v) {
  if (!Array.isArray(v)) return undefined
  const links = v
    .filter(isPlainObject)
    .map((l) => ({ label: str(l.label), href: str(l.href) }))
    .filter((l) => l.label && l.href)
  return links.length ? links : undefined
}

/**
 * Normalise the address a product may give as a string, a list of display lines,
 * or a structured object. Display `lines` are derived from the structured fields
 * when not given, so one brand.json field feeds both the contact card and the
 * JSON-LD PostalAddress.
 */
function normaliseAddress(a) {
  if (a === undefined || a === null) return undefined
  if (typeof a === 'string' || Array.isArray(a)) {
    const lines = strList(a)
    return lines.length ? { lines } : undefined
  }
  if (!isPlainObject(a)) return undefined
  const structured = {
    street: str(a.street || a.streetAddress),
    postalCode: str(a.postalCode),
    city: str(a.city || a.locality || a.addressLocality),
    region: str(a.region || a.addressRegion),
    country: str(a.country || a.addressCountry),
  }
  let lines = strList(a.lines)
  if (!lines.length) {
    lines = [
      structured.street,
      [structured.postalCode, structured.city].filter(Boolean).join(' '),
      structured.region,
      structured.country,
    ].filter(Boolean)
  }
  return prune({ lines, ...structured })
}

/**
 * brand.json `site` → content model fragment (layer 2). Deterministic key order so
 * the generated module is byte-stable for the same input.
 */
function brandSiteToContent(site) {
  if (!isPlainObject(site)) return {}
  const contact = isPlainObject(site.contact) ? site.contact : {}
  const social = isPlainObject(site.social) ? site.social : {}
  const footer = isPlainObject(site.footer) ? site.footer : {}
  const seo = isPlainObject(site.seo) ? site.seo : {}
  const analytics = isPlainObject(site.analytics) ? site.analytics : {}
  const navCta = isPlainObject(site.navCta) ? site.navCta : {}

  const provider = str(analytics.provider).toLowerCase()
  const businessType = str(seo.businessType)

  const out = {
    locale: str(site.locale),
    nav: {
      links: linkList(site.nav),
      ctaLabel: str(navCta.label),
      ctaHref: str(navCta.href),
    },
    contact: {
      email: str(contact.email),
      phone: str(contact.phone),
      address: normaliseAddress(contact.address),
      hours: strList(contact.hours),
      openingHours: strList(contact.openingHours),
    },
    footer: {
      tagline: str(footer.tagline),
      columns: Array.isArray(footer.columns)
        ? footer.columns
            .filter(isPlainObject)
            .map((c) => ({ title: str(c.title), links: linkList(c.links) }))
            .filter((c) => c.title && c.links)
        : undefined,
      social: Object.fromEntries(SOCIAL_KEYS.map((k) => [k, str(social[k])])),
      legalLinks: linkList(footer.legalLinks),
      copyright: str(footer.copyright),
    },
    seo: {
      titleTemplate: str(seo.titleTemplate),
      description: str(seo.description),
      ogImage: str(seo.ogImage),
      businessType: SCHEMA_TYPE_RE.test(businessType) ? businessType : '',
    },
    analytics: {
      provider: ANALYTICS_PROVIDERS.includes(provider) ? provider : '',
      id: str(analytics.id),
    },
  }
  return prune(out) || {}
}

/** Warnings for values brand.json carries that the mapping had to drop. */
function validateBrandSite(site) {
  const warnings = []
  if (!isPlainObject(site)) return warnings
  const bt = str(site.seo && site.seo.businessType)
  if (bt && !SCHEMA_TYPE_RE.test(bt)) warnings.push(`site.seo.businessType "${bt}" is not a schema.org type name — using ${DEFAULT_BUSINESS_TYPE}`)
  const provider = str(site.analytics && site.analytics.provider).toLowerCase()
  if (provider && !ANALYTICS_PROVIDERS.includes(provider)) warnings.push(`site.analytics.provider "${provider}" is not one of ${ANALYTICS_PROVIDERS.join('|')} — analytics disabled`)
  if (provider === 'umami' && !str(site.analytics.id)) warnings.push('site.analytics.provider "umami" needs site.analytics.id — analytics disabled')
  if (site.nav !== undefined && !Array.isArray(site.nav)) warnings.push('site.nav must be an array of { label, href }')
  return warnings
}

/** Source of client/src/app/content/@generated/site.brand.js. */
function generateSiteBrandModule(site, { companyName = '' } = {}) {
  const content = brandSiteToContent(site)
  const body = JSON.stringify(content, null, 2)
  return `// @generated — informational site content from the repo-root brand.json \`site\` block.
// ${SITE_GENERATED_MARKER} — DO NOT EDIT BY HAND; edit brand.json and run \`npm run apply-brand\`.
//
// Layer 2 of 3 in client/src/config/index.js (lowest → highest precedence):
//   content/@system/site.js  →  THIS FILE  →  content/@custom/site.js
// Objects merge per key, arrays replace, unset keys fall through (scripts/lib/site-brand.cjs).
// Company: ${companyName || '(unnamed)'}

export default ${body}
`
}

module.exports = {
  SITE_GENERATED_MARKER,
  SOCIAL_KEYS,
  ANALYTICS_PROVIDERS,
  DEFAULT_BUSINESS_TYPE,
  deepMerge,
  mergeSiteLayers,
  brandSiteToContent,
  validateBrandSite,
  generateSiteBrandModule,
  normaliseAddress,
  prune,
}
