// @system — Auto-generated barrel (do not edit manually)
// Generated by: scripts/@system/generate-barrels.js
//
// Feature modules: routers are mounted only when their module is enabled in
// brand.json `modules` (see lib/@system/Helpers/modules.js → ROUTER_MODULES).
// Disabled routers are not require()d at all.

const express = require('express')
const { isRouterEnabled } = require('../../lib/@system/Helpers/modules')
const router = express.Router()

function mount(name, requirePath) {
  if (isRouterEnabled(name)) router.use(require(requirePath))
}

mount('activity', '../../api/@system/activity')
mount('admin', '../../api/@system/admin')
mount('ai', '../../api/@system/ai')
mount('api-keys', '../../api/@system/api-keys')
mount('auth', '../../api/@system/auth')
mount('blog', '../../api/@system/blog')
mount('brands', '../../api/@system/brands')
mount('communications', '../../api/@system/communications')
mount('contact', '../../api/@system/contact')
mount('csrf', '../../api/@system/csrf')
mount('docs', '../../api/@system/docs')
mount('email', '../../api/@system/email')
mount('gdpr', '../../api/@system/gdpr')
mount('ghost', '../../api/@system/ghost')
mount('health', '../../api/@system/health')
mount('integrations', '../../api/@system/integrations')
mount('notifications', '../../api/@system/notifications')
mount('oauth', '../../api/@system/oauth')
mount('onboarding', '../../api/@system/onboarding')
mount('payments', '../../api/@system/payments')
mount('ping', '../../api/@system/ping')
mount('polar', '../../api/@system/polar')
mount('retention', '../../api/@system/retention')
mount('robots', '../../api/@system/robots')
mount('search', '../../api/@system/search')
mount('sessions', '../../api/@system/sessions')
mount('sitemap', '../../api/@system/sitemap')
mount('storage', '../../api/@system/storage')
mount('stripe', '../../api/@system/stripe')
mount('subscriptions', '../../api/@system/subscriptions')
mount('teams', '../../api/@system/teams/router')
mount('threads', '../../api/@system/threads')
mount('totp', '../../api/@system/totp')
mount('usage', '../../api/@system/usage')
mount('user', '../../api/@system/user')
mount('web3', '../../api/@system/web3')
mount('webhooks', '../../api/@system/webhooks')

module.exports = router
