/**
 * Brand Assets Validation — validates that all brand assets (logo, favicon, OG image, thumbnail)
 * are correctly generated for Creative Portfolio (portfolio-demo).
 *
 * Verifies:
 *   1. Brand JSON configuration has the correct portfolio-demo identity
 *   2. SVG source files exist in assets/ with correct brand markup
 *   3. Derived PNG assets exist in client/public/ after generate-brand-assets
 *   4. Generated @custom/info.js stays in sync with brand.json
 */
import { describe, it, expect } from 'vitest'
import fs from 'fs'
import path from 'path'
import { info } from '@/config'
import brandConfig from '../../../../brand.json'

const ROOT = path.resolve(__dirname, '../../../..')

function fileExists(relPath) {
  return fs.existsSync(path.join(ROOT, relPath))
}

describe('Creative Portfolio brand configuration (brand.json)', () => {
  it('has the correct company name', () => {
    expect(brandConfig.companyName).toBe('Creative Portfolio')
  })

  it('has the portfolio-demo slug', () => {
    expect(brandConfig.slug).toBe('portfolio-demo')
  })

  it('has the portfolio template type', () => {
    expect(brandConfig.templateType).toBe('portfolio')
  })

  it('uses a vibrant purple primary color', () => {
    expect(brandConfig.primaryColor).toBe('#8B5CF6')
  })

  it('uses amber accent color', () => {
    expect(brandConfig.accentColor).toBe('#F59E0B')
  })

  it('defaults to dark theme', () => {
    expect(brandConfig.defaultTheme).toBe('dark')
  })
})
describe('Creative Portfolio SVG logo source files (assets/logos/)', () => {
  it('has logo.svg (horizontal wordmark + mark)', () => {
    expect(fileExists('assets/logos/logo.svg')).toBe(true)
    const content = fs.readFileSync(path.join(ROOT, 'assets/logos/logo.svg'), 'utf8')
    expect(content).toContain('Creative Portfolio')
    expect(content).toContain('#8B5CF6')
    expect(content).toContain('#F59E0B')
  })

  it('has logo-mark.svg (square mark, source for derived assets)', () => {
    expect(fileExists('assets/logos/logo-mark.svg')).toBe(true)
    const content = fs.readFileSync(path.join(ROOT, 'assets/logos/logo-mark.svg'), 'utf8')
    expect(content).toContain('Creative Portfolio')
    expect(content).toContain('#8B5CF6')
  })

  it('has logo-white.svg for dark backgrounds', () => {
    expect(fileExists('assets/logos/logo-white.svg')).toBe(true)
  })

  it('has logo-dark.svg for light backgrounds', () => {
    expect(fileExists('assets/logos/logo-dark.svg')).toBe(true)
  })

  it('has logo-on-dark.svg for display on dark backgrounds', () => {
    expect(fileExists('assets/logos/logo-on-dark.svg')).toBe(true)
  })

  it('has logo-on-light.svg for display on light backgrounds', () => {
    expect(fileExists('assets/logos/logo-on-light.svg')).toBe(true)
  })

  it('has logo-wordmark.svg', () => {
    expect(fileExists('assets/logos/logo-wordmark.svg')).toBe(true)
    const content = fs.readFileSync(path.join(ROOT, 'assets/logos/logo-wordmark.svg'), 'utf8')
    expect(content).toContain('Creative Portfolio')
  })
})
describe('Creative Portfolio favicon source (assets/favicons/)', () => {
  it('has the favicon SVG source file', () => {
    expect(fileExists('assets/favicons/favicon.svg')).toBe(true)
    const content = fs.readFileSync(path.join(ROOT, 'assets/favicons/favicon.svg'), 'utf8')
    expect(content).toContain('#8B5CF6')
    expect(content).toContain('#F59E0B')
  })
})

describe('OG image source files (assets/og/)', () => {
  it('has og-image.svg for social sharing', () => {
    expect(fileExists('assets/og/og-image.svg')).toBe(true)
    const content = fs.readFileSync(path.join(ROOT, 'assets/og/og-image.svg'), 'utf8')
    expect(content).toContain('Creative Portfolio')
    expect(content).toContain('#8B5CF6')
  })

  it('has og-thumbnail.png thumbnail', () => {
    expect(fileExists('assets/og/og-thumbnail.png')).toBe(true)
  })
})
describe('Derived brand assets in client/public/ (generated by generate-brand-assets.js)', () => {
  it('has generated logo.png (512x512)', () => {
    expect(fileExists('client/public/logo.png')).toBe(true)
    const stat = fs.statSync(path.join(ROOT, 'client/public/logo.png'))
    expect(stat.size).toBeGreaterThan(1000)
  })

  it('has generated favicon.ico (multi-size)', () => {
    expect(fileExists('client/public/favicon.ico')).toBe(true)
    const stat = fs.statSync(path.join(ROOT, 'client/public/favicon.ico'))
    expect(stat.size).toBeGreaterThan(100)
  })

  it('has generated favicon-16x16.png', () => {
    expect(fileExists('client/public/favicon-16x16.png')).toBe(true)
  })

  it('has generated favicon-32x32.png', () => {
    expect(fileExists('client/public/favicon-32x32.png')).toBe(true)
  })

  it('has generated apple-touch-icon.png (180x180)', () => {
    expect(fileExists('client/public/apple-touch-icon.png')).toBe(true)
    const stat = fs.statSync(path.join(ROOT, 'client/public/apple-touch-icon.png'))
    expect(stat.size).toBeGreaterThan(500)
  })

  it('has generated icon-192.png (PWA manifest)', () => {
    expect(fileExists('client/public/icon-192.png')).toBe(true)
  })

  it('has generated icon-512.png (PWA manifest)', () => {
    expect(fileExists('client/public/icon-512.png')).toBe(true)
  })

  it('has generated og-image.png (1200x630)', () => {
    expect(fileExists('client/public/og-image.png')).toBe(true)
    const stat = fs.statSync(path.join(ROOT, 'client/public/og-image.png'))
    expect(stat.size).toBeGreaterThan(5000)
  })
})

describe('Generated @custom/info.js sync with brand.json', () => {
  it('keeps brandColor aligned with brand.json primaryColor', () => {
    expect(info.brandColor).toBe(brandConfig.primaryColor)
  })

  it('keeps accentColor aligned with brand.json accentColor', () => {
    expect(info.accentColor).toBe(brandConfig.accentColor)
  })

  it('keeps the product name aligned with brand.json companyName', () => {
    expect(info.name).toBe(brandConfig.companyName)
  })

  it('keeps the default theme aligned with brand.json defaultTheme', () => {
    expect(info.defaultTheme).toBe(brandConfig.defaultTheme)
  })

  it('exposes a non-empty logo path', () => {
    expect(typeof info.logo).toBe('string')
    expect(info.logo.length).toBeGreaterThan(0)
  })
})
